export const MONSTER_MATCH_REQUEST = 'MONSTER_MATCH_REQUEST'
export const MONSTER_MATCH_SUCCESS = 'MONSTER_MATCH_SUCCESS'
export const MONSTER_MATCH_FAIL = 'MONSTER_MATCH_FAIL'

export const IPFS_UPLOAD_REQUEST = 'IPFS_UPLOAD_REQUEST'
export const IPFS_UPLOAD_SUCCESS = 'IPFS_UPLOAD_SUCCESS'
export const IPFS_UPLOAD_FAIL = 'IPFS_UPLOAD_FAIL'

export const RANDOM_MONSTER_REQUEST = 'RANDOM_MONSTER_REQUEST'
export const RANDOM_MONSTER_SUCCESS = 'RANDOM_MONSTER_SUCCESS'
export const RANDOM_MONSTER_FAIL = 'RANDOM_MONSTER_FAIL'